### PR TITLE
Fixes NTTCP-11. Makes send strict for self connections.

### PR DESCRIPTION
**Pull request by facundominguez**
https://cloud-haskell.atlassian.net/browse/NTTCP-11

### CODE REVIEW

**Comment by edsko** [comment]
What is the motivation for this change, OOC?

**Comment by edsko** [comment]
Basically this change is making send strict for _all_ connections, is that true?

**Comment by facundominguez** [comment]
Send is strict for all connections to other endpoints. This patch is making it strict for the same endpoint as well.

I can think of two reasons to do it:
 * Have semantics of send invariant regardless of who the receiver is.
 * To make a mistakes easy to find.

Before this change. You could crash the node controller of CH by calling:
```Haskell
DP.spawnAsync self (error "bang!")
```
which is going through the transport even for the local node.

If the sender gets the error, it is less puzzling.

**Comment by qnikst** [comment]
This is part of `connectToSelf` call that is called inside:

```
apiConnect params ourEndPoint theirAddress _reliability hints =
  try . asyncWhenCancelled close $
    if localAddress ourEndPoint == theirAddress
      then connectToSelf ourEndPoint
```

so I'd say that this patch do not affect non-local connections in any way.

**Comment by edsko** [comment]
Yes, that's what I meant: it was already strict when sending to other endpoints, this patch makes it strict for same-endpoint too. Makes sense, although Tim had some "unsafe" primitives that explicitly were NOT strict when sending stuff to the same endpoint. I don't know if that is affected by this patch or not.

**Comment by qnikst** [comment]
IIUC that part of functionality is not affected, because `d-p` do not use `network-transport` for local communication.

**Comment by edsko** [comment]
You may well be right, I don't remember :) But that sounds reasonable :) Mentioned it just in case.

**Comment by qnikst** [comment]
@edsko while you are here could you also check #18 ?

**Comment by facundominguez** [comment]
@qnikst pointed that `evaluate` is not contributing anything, so I shortened the patch.

**Pull request merged**
